### PR TITLE
closes #41 Handle delete message from streaming

### LINKED ISSUE #41: Can not parse delete event
Sometimes I receive delete event, but megalodon can not parse it.

```
  [22:07:59.204] [error] Error: Error parsing websocket reply: {"event":"delete","payload":"9iXBSXHXQfkDAQiJhA"}, error message: SyntaxError: Unexpected token i in JSON at position 1
      at Parser.parser (/home/akira/src/github.com/h3poteto/whalebird-desktop/node_modules/megalodon/lib/web_socket.js:169:32)
      at WebSocketConnection.<anonymous> (/home/akira/src/github.com/h3poteto/whalebird-desktop/node_modules/megalodon/lib/web_socket.js:103:30)
      at WebSocketConnection.emit (events.js:182:13)
      at WebSocketConnection.processFrame (/home/akira/src/github.com/h3poteto/whalebird-desktop/node_modules/websocket/lib/WebSocketConnection.js:554:26)
      at /home/akira/src/github.com/h3poteto/whalebird-desktop/node_modules/websocket/lib/WebSocketConnection.js:323:40
      at process._tickCallback (internal/process/next_tick.js:61:11)
```

The payload is a string, but megalodon parse the payload as JSON: https://github.com/h3poteto/megalodon/blob/master/src/web_socket.ts#L206
So, it is failed.

### PR DESCRIPTION
**Pull request by h3poteto**

### CODE REVIEW

File: src/parser.ts [hunk 1]
```diff
@@ -52,30 +52,33 @@ class Parser extends EventEmitter {
...
+            break
+          case 'notification':
+            this.emit('notification', jsonObj as Notification)
+            break
+          case 'conversation':
+            this.emit('conversation', jsonObj as Conversation)
+            break
+          case 'delete':
+            // When delete, data is an ID of the deleted status
+            this.emit('delete', data as string)
```
Comment (h3poteto) [inline src/parser.ts]: __[TSLint]__ This assertion is unnecessary since it does not change the type of the expression. (no-unnecessary-type-assertion) ([link](https://sider.review/gh/repos/136549493/pulls/42#issue-4117604))

<sub>posted by Sider</sub>

File: src/web_socket.ts [hunk 2]
```diff
@@ -200,28 +200,37 @@ class Parser extends EventEmitter {
...
+        this.emit('update', mes as Status)
+        break
+      case 'notification':
+        this.emit('notification', mes as Notification)
+        break
+      case 'conversation':
+        this.emit('conversation', mes as Conversation)
+        break
+      case 'delete':
+        this.emit('delete', payload as string)
```
Comment (h3poteto) [inline src/web_socket.ts]: __[TSLint]__ This assertion is unnecessary since it does not change the type of the expression. (no-unnecessary-type-assertion) ([link](https://sider.review/gh/repos/136549493/pulls/42#issue-4117605))

<sub>posted by Sider</sub>
